# SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Release
on:
  release:
    types: [published]

jobs:
  publish_artifact:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            SHIP: ship-linux
            FILE: release/OpossumUI-*.AppImage
          - os: macos-latest
            SHIP: ship-mac
            FILE: release/mac/OpossumUI.zip
          - os: windows-latest
            SHIP: ship-win
            FILE: release/OpossumUI Setup*.exe

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --network-timeout 560000
      - run: yarn ${{ matrix.SHIP }}
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.FILE }}
